version: '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    volumes:
      - .:/opt/app/api
    restart: always
    expose:
      - '8080'
    ports:
      - 80:8080
    env_file:
    - ./sql/.envs/.mysql
    depends_on:
      - db
  
  db:
    image: mysql:8
    expose:
      - '3306'
    ports:
      - 3305:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    env_file:
    - ./sql/.envs/.mysql

volumes:
  db_data: {}